git add "./index.org"
git add "./Computer Communications/cc_notes.org"
git add "./Computer Communications/Computer Networking. A Top Down Approach, 7th.org"
git add "./Computer Communications/images/*"
git add "./ATA I/Eric Zürcher-Book (English).org"
git add "./ATA I/at1_notes.org"
git add "./Formations of modernity/fm_notes.org"
git add ".github"
git add "gitcommit.sh"
git commit -m "Update notes"
