#+AUTHOR: Denis Davidoglu

* ITB 020E - Formations of Modernity
** Time & place
   - Tuesday 11:30-14:29, FEB D204
** Grading
   - Midterm 40%
   - Final 50%
   - Attendance 10%
** Reading by weeks
   1. Introduction: What is Modern ? 
   2. The Rise of Europe: Renaissance, Reform and Reconnaissance 
	  - Norman Davies, Europe: A History, pp 469-503 (Chapter VII Renatio)
	  - Niccolo Machiavelli, “The Prince”
	  - Martin Luther, “The Freedom of a Christian”
	  - John Calvin, “The Institutes of the Christian Religion”
   3. The Development of the Modern State
	  - Stuart Hall, Bram Gieben (ed), Formations of Modernity, David Held, “The Development of the Modern State”, pp 71-125
   4. Enlightenment and the French Revolution
	  - Norman Davies, Europe: A History, pp 596-614, 675-733 (Chapters Lumen and Revolutio)
	  - Thomas Hobbes, “Leviathan”
	  - John Locke, “Second Treatise of Government”
	  - Jean Jacques Rousseau, “The Social Contract”
	  - Thomas Jefferson, “The Declaration of Independence”
   5. Liberalism and Nationalism; the Best of the Times
	  - Norman Davies, Europe: A History, pp 782-835 (Chapter X, Dynamo)
   6. The Rise of Socialism and Communism 
	  - Norman Davies, Europe: A History, pp 835-865 (Chapter X Dynamo)
	  - Karl Marx, Friedrich Engels, The Communist Manifesto 
	  - Charles Darwin, “The Descent of Man”
	  - Friedrich Nietzsche, “Beyond Good and Evil”
	  - Sigmund Freud, “The Interpretation of Dreams”
	  - George Orwell, “Shooting an Elephant”
   7. Imperialism, Fascism and World Wars
	  - Eric Hobsbawm, The Age of Extremes, pp 21-53
	  - Mark Mazower, The Dark Continent, pp 77-105 
   8. Midterm
   9. Cold War and the Age of Intellectuals
	  - Tony Judt, Reappraisals, pp. 95-146
	  - Nikita Kruschev, “Report to the Communist Party Congress”
	  - Winston Churchill, “The Iron Curtain”
   10. The Rise of the Modern Economy 
	   - Stuart Hall, Bram Gieben (ed.), Formations of Modernity, Vivienne Brown,    
	   - “The Emergence of the Economy”, pp. 127-175
   11. 1968 and Beyond: The Rise of Identity Politics 
	   - Tony Judt, Postwar, London: The Penguin Press, 2005, pp. 390-421
   12. The End of History or Clash of Civilizations ?
	   - Francis Fukuyama, “The End of History ?”, National Interest, Spring 1989
   13. The Age of Populism
	   - Jan-Werner Müller, What is Populism, Philadelphia: University of Pennsylvania Press, 2016, pp. 1-40
   14. Conclusions
** Notes
*** Week 2
*** Week 3
    - Protestant reformation is important because it signals emergence of modern ideas.
    - Subjectivity, relativity, ambiguity.
    - Stop popes speaking in the name of god. Popes were "innoncent", could not make mistakes
    - Pope was intermediate between God and humans.
    - Existance of God was undoubtable.
    - There a skeptics in the 17th century, concept of Theodicity.
    - Theodicity: the existance of evil. Why evil exists if there is God and salvation?
      + It is a challange that humans accept.
      + Then the question is why do premature deaths happens?
    - Silence Scorsese (2016) trailer.
      + Jesuits try to convert Japanese to Catholisism.
      + Many missions. And 2-3% India, Japan, China.
      + Missions stopped when Japanese banned Europeans from entering Japan expect in trading ports.
      + Punishment for being Christian in Japan is burning alive.
      + If you step on cross, you survive and can convert other people to Christianity.
      + If you don't step, you sacrifice yourself for the religion.
      + What should you do? Why is God silent?
    - Zoroastrism is about evil and good, there a two Gods.
    - Satan is powerful and is answer of why there exists evil.
    - Omnipotence, omnipresence, omniscience and God questioning.
      + If God is omnipotent, there is no free will. If there is free will, God is not omnipotent.
      + Baruch Spinoza's solution is that God is everywhere. We act with the will of God.
      + God doesn't care about what we do everytime.
      + He links nature to God.
      + God is not somewhere far away.
      + Abstraction of God.
      + God is not an entity that punishes
      + Judaism is not about prohibition or rituals.
      + If you act ethically, this is God.
    - Kabala, Jewish sect.
      + If everything is compliant with nature, there will be no evil.
      + Perfection of God = no evil.
      + Once humans act with their conciosness, no evil.
    - In the 17th century, God is totally abstracted in comparison with Zeus and Christian and Islamic God.
    - Fear God or love God?
    - God sets the clock and it's up to humans to act. Agency of God. God is taken from with world, and placed in other world to be judge.
    - Immanuel Kant
      + God is idea, spirits
      + Humanities aim is salvation by doing good things
      + Focuses about ethics
    - After Enlightment, Christianity turns into individual.
    - Islam is about collectively feeling God
    - Why do kings exist? Protector of authority and order.
    - Legitimacy of sultans comes from power, brothers fight for the throne.
    - How did the first king on the world appear?
      + Thomas Hobbes
      + Leviathan's cover. King consists of many people.
      + People chose the wisest.
      + If people are not happy anymore with the king, they cannot take his authority back.
      + If people put someone they can take the authority back, there is no meaning in choosing the king in the first place.
      + Decisions are not irrevocable.
      + Author is not authority yalakalisi, but against republic.
      + Fear is my twin, born prematurely because his moms of fear of Spanish invasion.
      + In the 17th century the establishment of republic in England didn't work.
      + Kings used to hold incredible power, but now parliament will do that.
      + People in parliament cannot agree with each other on using the incredible power.
      + King had final authority.
      + King commanded the powerful military. Parliaments were couped by militaries now.
      + Oliver Cromwell. Ataturk - Turkish Cromwell, powerful military leader who practices politcal power.
      + When Thomas Cromwell died, his son became dictator.
      + Trend of kings.
      + If there are no kings, there would be chaos, violence. We need kings. (Thomas Hobbes)
      + The real authority is king
    - John Locke
      + Struggle with wild life, dangers. First humans needed to colaborate. They chose the wisest to take decisions.
      + Same as Thomas Hobbes reasoning.
      + When they chose the leader, they gave them common rules to serve the community. If the king violates, he will be annulled.
      + No revolution, just take the authoritive from the king.
    - Popularization of the idea that king can be overthrown. Jean-Jacques Rousseau.
      + The real authority is people.
    - No difference between king and state. King can violate his own laws, therefore creating new laws.
    - In Rome, there was a clear differentiation between state and the king.
    - Sovereignity
      + In monarchy, sovereignty belongs to king and king's body
      + Church, king, land had some sovereignty.
      + In modern time, sovereignty cannot be shared.
      + Enlightment idea: sovereignty belongs to the people
    - Rousseau thinks that elections are bad
    - Cambodgia the wildest dictator ever lived
      + Labour camps for burgeouse
      + 1 ML died
      + People who wear glasses should be punished
    - Nobody gave you human rights, so nobody can take them from you. You were born free man.
    - Declaration of Independence of USA - one of the best Enlightenment texts.
      + ...which impel them to the separation
      + Motivate the war with the fact that they have the human right to separate
      + Not "we, the leaders", but "we, the people", the delegates
      + All men are created equal. No explanation needed.
      + God gave liberty, dignity, pursuit of happiness, no state can take them.
      + To protect our rights, they need a new state. Legitimizing government.
      + Reffers to God in many places but with other names. Deist text. Not Christian God.
	#+begin_quote
	The unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.

We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.
	#+end_quote
    - Fyodor Doestoyevky supports that moral values are give only by God. Crime and Punishment.
    - People motivate their liberty and rights with the existence of a Creator.
*** Week 4
**** Recap from last week
     - We talked that In englightment is science against religion. But this misses the core.
     - Understanding of nature, human soul and social order
     - In the hierarchy of kingdoms, nobody could image another *moral order*.
     - Religions failed to exists in the politics in Europe in the enlightment
     - Before the modern age, religions aim to constitute the social order
     - Secularism was not possible, church must say something about politics
**** French revolution
     - Liberty leading the people painting (1830), not related to the *real* french revolution
     - Bourgeoisie runs the revolution
     - King was struggling with poverty affecting peasant. He didn't want to take the resposibility.
     - Parliament takes the resposiblity, nobility
     - French parliament represents three orders
       1) order - clergy
       2) order - aristocracy
       3) order - third estate (everybody else)
     - Land was the money generator
     - In 16th century, colonialism became more profitable. Huge plantations.
     - More people became rich, because the wealth didn't depend on the land possesions
     - Aristocrats were descendants Roman commanders, conquered the land. Not bought and sold.
     - Overseas trade and proto-industry
     - Clergy always comes from aristocracy
     - Clergy and aristocrats are not legally equal to others
     - Noble from birth, not becoming noble
     - Siyes, "What is the third estate?"
       + What is the third estate? Everything
       + What had it been so far in the political order? Nothing
       + What does it ask to be? Something
       + Political and economic realities should be related and balanced
     - "Oath of the tennis court" painting. Jews defend their right of the third estate.
     - Parliament made coup, took the king into custody, and became the ruling power. General Assembly. Third Estate becomes the majority.
     - Abolishment of priveledges of noble people, including land.
     - Colonel Alfred Dreyfus. First Jewish colonel in the French army late 19th century. Persecuted.
     - J'Accuse, book about Alfred Dreyfus.
     - France was shuttered for a century. Left - proDreyfus, Right - anti Dreyfus.
     - Paths of glory movie. French commmanders.
     - After 1950's military lost political power.
     - Land becomes a commodity
     - Nobles are noble not because the state give them the title, but because they are noble. They are beyond the state.
     - Papacy owned huge lands in France. "God" gave the land, and the state cannot revoke it.
     - Clergy cannot give oath to the state, because God is always higher than the state. If state and God clushes, they would choose God.
     - In Islamic states, state regulates the religion, and all state people are religious.
     - French King escaped custody and fled to Germany
     - What to do with the king?
       + Execute :). "A king should reign or die" Saint-Just 1792
       + King is dangerous if he lives and not reigns
       + Menderes reference
     - Tyran is an important model. Tyran is power-grabber. Not a king, but acts like one.
     - Many people were against the Republic
     - Those against revolution are considered traitors
     - Parliament has the authority and right to sentence people
     - Many people suspected are executed
     - Productive session of executing using Guillotine™, head combo
     - Jacobin era, age of terror (fear)
     - Saint-Just is part of Jacobites
     - Georges Danton thought that it is dangerous to execute people like that. Also executed.
     - Many bolshevics were executed by themeselves too. All revolutions are like this.
     - In revolution, you should act fast, even if there is no crime, you should act to prevent any crime.
     - George Bush preventively attacked Iraq
     - Authority of the king cannot be questioned. Authority of a random elected tyran is questionable.
     - Solution was Napoleon, military commander. Napoeleon becomes the council of revolution.
     - Napoleon is called revolution on horseback. He acts by raging wars.
     - Liberty, equality, brotherhood. Beethoven 9th semphony is about liberal ideas in french revolution.
     - Beethoven 5th symphony is dedicated to Napoleon. "To memory of a great man". Napoleon betrayed himself in the French revolution.
     - Napoleon is not king, he is emperor.
     - Napoleon was coronated. Embarrasment of the Pope, became a legitimate emperor by himself.
     - Young - liberal republical nationalist
     - Public debates, newspapers, gossips. It is harder to become a king with absolute authority.
     - Challenging a king to not be a king
     - King symbolizes moral order, christianity, patriarchal values. Parliament thinks that without a king, there would be chaos. King is the only way of legitimate political order.
     - In Turkey there is no movement of bringing the Ottoman dynasty back, interesting.
     - In France reactionsist wanted to undo every change of French Revolution, half of people throughout the 19th century supported this.
     - French Revolution didn't end, it started a period of battles.
     - Ultraroyalists.
     - In 1830, constitutional monarchy is established with a king.
     - Karl Marx says: History repeats twice: first time is tragedy, the second time is farce
     - 1883 the last royal family member died
     - White is the symbol of conservatism. Bourbon flag of France.
*** Week 5
**** Anachronism
	 - A misplacing or error in the order of time; an error in chronology by which events are misplaced in regard to each other, esp. one by which an event is placed too early; falsification of chronological relation.
	 - In movies, people are made to think like modern people
	 - It is misleading to think about China, Ottomans as states. They were called "polity".
	 - In a state, there is a law, there are citizenships, sovereignty.
**** Premodern states
	 - Weak states
	 - No means of imposing taxes
	 - There was feudalism all over the world. Local dynasties, churches.
	 - States are military machines
	 - Taxes: from 1% in medieval ages to 20-30% in modern ages
	 - States didn't care about proving their legitimacy for local people, only for elite
	 - Peasants were not German, French, Turks, they were just peasants.
	 - Public lynching, killing of criminals
**** Birth and rise of the modern state
	 - 19th century
	 - Max Webel, socialist, studied the state. Defined the state as a legal monopoly to use violence. Criminals are caught by police.
	 - State is not something to be obeyed, but it should provide social services. 
	 - Taxes, laws, infrastructure
	 - Centralized
	 - The emergence of strong armies lead to modern states
	 - Free education, using the human capital
	   + 1890's, France and Germany introduces compulsory education
	   + In United States, there was no education, but migrants were literate and the country was more developed.
	   + Universities in USA were private, established by people, charity. Late 19th century.
	   + Oxford, Cambridge were originally religious schools.
	 - Free healthcare
	 - People can be certain about their future
	 - Hidden costs
**** Military campaigns
	 - Military campaigns were sophisticated organizations. Local people were responsible for the organization.
	 - According to Islamic law, if the state surrender, you cannot plunder. If you win, you can plunder for three days. Kill, rape, rob.
	 - Victories were desirable for the soldiers.
	 - Albanians were the gangsters of Balkans, who joined Ottomans in the Vienna campaign.
	 - In modern age, soldiers have no right to plunder, because they are paid by the state.
	 - Ottomans could not afford a strong army, they should be paid in gold coins
	 - Britain took loans to finance a 4-year long war. Britain's Bank issued money, legal tenders. Banknotes are the debts of a state. 17th century.
**** Modern countires are defined by nations
	 - Common language, common ethnicity in a broad sense
	 - Minorities are seen odd in nationist states
	 - How French became French? Peasant needed to become proper French by means of education.
	 - The place of history in education is to create a national identity.
	 - History is told in different ways in different places, even within a country. People can be offended or just feel irrelevant, "this is not my history".
	 - In reality, states have created nations. "We established Italy, now we need to establish Italians".
	 - Strong militaries created states.
	 - Language is something colonial.
	 - You have to be loyal to state, because it represents your nation.
	 - E-Devlet is horrifiying.
*** Week 6
**** A tale of two cities
	- Humans have their own agency to act, change and transform. There was no such passion in 16th century.
	- "It was the best of times, it was the worst of times, it was the age of wisdom."
	- Enlightments, understanding, but it's stupid that people kill each other more than ever.
	- Common logic in revolutions.
**** 9th symphony of Beethoven. 
	 - He uses human words in the symphony, because its more relatable to humans. Contrasts of good and evil.
	 - Idea of French revolution, all men become brothers.
	 - Tranquility, peace in front of the most beautiful thing, mother nature.
	 - World views and political views.
**** Sorrows of Young Werther, Goethe
	 - Idealistic, naive, not knowing the bad. He thinks that he is completely uncorrupted and too naive for this world, so he commits suicide.
**** Les Miserables
	 - Hugo is the ultimate romantic
**** Not all romantistist support the French revolution
**** Madame Bovery, Gustave Flaubert
	 - Manifesto of anti-romantisism. Romantic ideas misrepresent the reality and are futile. Realism.
	 - in 1850's romantisism dies, materialism begins
**** Dostoyevski
	 - He hated socialists and anarchists, all his books are political
	 - If there is no god, everything is permissible
	 - Crime and punishemnt: Is the human nature good or bad?
	 - Church is the authority that supervises the morals.
	 - The believe that when people take control in their hands ended with people destroying everything
**** Relation of republicanism and nationalism
	 - The sovereignty belongs to the magical word "people", parliament
	 - In France, these people happen to be French
	 - No ethnic or cultural meaning to "French"
	 - There is no need to be ethnic French to be part of French nation
	 - Chopin introduced folk melodies into classical music. He was not a nationalist, but he knew that using folk melodies is something valuable.
	 - Every nationalist movement discovered folk poetry, melodies, legends.
	 - National sovereignty becomes as important as dynasty sovereignty. Create bonding with the people, to gain legitimacy.
**** European flags
	 - Three colors on a flag is the symbol of republic.
	 - Cross is the coat of arm of the dynasties.
	 - Star on the Turkey's flag means Google review
*** Week 7
**** Manifesto of Communist Party
	 - Explain perspective of future in a scientific way
	 - Communism is like spectre, ghost. It does not exists, but you feel you. Contrary to material things, it is more frightening.
	 - Pope and Tsar, metternic and quizaot, French radical and  german police spies are all opposite, but they would unite against Communism.
	 - History is class struggles, everything else is secondary
	 - Society is formed of opressed and opressors
	 - Class antagonism was not ended by the modern bourgeois, but new conditions of oppression were created
	 - Adam Smith, Wealth of nations. High prices were regulated by moral values.
	 - Economics is not something you can see. Economics are theorized, assumed. It is not a full science.
	 - Wages are on the subsistence level, enough for surviving. Workers cannot save money.
	 - Thomas Malthus (priest): in economics there is no place for morality, there is only reality. Even God cannot do anything.
	 - If workers are together and demand, they can bargain wages.
	 - Marx was saying that the current economic model is not sustainable and soon will colapse
	 - Bourgeoisie and Proletariat.
	 - For communists, economy was static and not developing for years, but it was actually not.
	 - "Bourgeoisie, historically, has played a most revolutionary part." Innovative, technological products.
	 - Slave-master relation became only naked self-interest cash payed relation, with no more metaphysics, God, enthusiasm
	 - Bourgeoisie even reduces family relation to a mere money relation. Women can be paid less, because men are the ones who bring money.
	 - Engels: modern marriage is prostitution, buy sexuality for a life
	 - Religion is opium of the people. Escape the reality and get relieved.
	 - William blake's drawings: you cannot draw such things without consuming opium. Religion in not a reason, it is a conclusion. They want the next world.
	 - Bourgeoisie does not care about religion, they are happy
	 - As feudalism ended, capitalism will end.
	 - Masses rise from the 20th century, rise of fascism. Problem of mass politics.
	 - You cannot quantify human factor. Sociology is not theorizable.
	 - Proletarians have nothing to lose but their chains. Working Men of All Countires, Unite!
	 - Minimum wage, two weeks of holidays, retirement wage, free education, healthcare were introduced after the communist manifesto was published.
	 - Proletarians have things other than chains.
	 - Capitalism started to offer benefits to workers
	 - Socialists were supporting not revolution but reformism
	 - Social-democracy
**** Militarism
	 - Not about armies, but army is necessary, to win a war.
	 - Militarism is about non-military affairs.
	 - Treating all aspects of life as military
	 - Everybody was shocked about Prussia defeating France
	 - Prussian king declared himself as a German king
	 - Berlin is not a natural place for Germany's capital. It was the Prussia's capital.
	 - Mountainous regions are more military. They are poorer and need to survive.
	 - Prussia has an army with people. Not people with army.
	 - Japanese modeled Purssia. The only way to resist European influence is to be military.
	 - Bulgaria, Ottomans
	 - Von der Goltz wrote "Nation in Arms", "Millet-i Muselleha".
	 - Nationalism, the way for mobilizing people.
	 - Children should be hearing military marches in kindergarten, not romatic and folk stories, which soften their hearts.
	 - Total war, everything is a part of warfare, the hymn of militarists.
	 - Everybody knew that when the war comes, it will be disastrous.
**** Week 11. Fascism and WWII
***** WWI results
	  - Destroyed aristocratic power in Britain, Germany, Austria
	  - Emergence of modern national state
	  - Elections, democracy

***** Mid 1920's
	  - Countries began to be ruled by new authoritarian parties.
	  - Italy, Mussolini in 1922.
	  - Many political parties that could not rule, and Mussolini promised stability.
	  - Became a dictator in a few years. Exile, kill, terrorize opponents.
	  - First dictators. Napoleon was elected with plebiscite, vote yes or no.
		#+begin_quote
	  Plebiscite n. [F. pl['e]biscite, fr. L. plebiscitum.]
	  A vote by universal male suffrage; especially, in France, a
	  popular vote, as first sanctioned by the National
	  Constitution of 1791
		#+end_quote
	  - Popular support, national interest equals me
	  - Democracy experiment enabled the spread of unspoken ideas. Rise of right-wing populist leaders.
	  - To the surprise of many, the first government was established by social-democrats in Germany.
	  - Berlin is compared to Babylon, for it was the capital of gays.
	  - The rise of free women. Bob haircut. Feminism emerged, because women replaced the men in economy during WWI.
	  - Suffragettes in UK
		#+begin_quote
    n 1: a woman advocate of women's right to vote (especially a
         militant advocate in the United Kingdom at the beginning of
         the 20th century)
		#+end_quote
	  - Hatred towards WWI, Jews, rich, politicians resulted in election of fascists.
	  - Pacifism lead to more authoritarian solutionx
	  - Christopher Isherwood, gay.
	  - Cabaret movie (1972). "Tomorrow belongs to me".
	  - Marburg Files
	  - Triumph of the Will, one of the best documentary. 16 years of German suffering (democracy was not seen good).
	  - A youth which knows no classes or castes. Sinifsiz imtiyasiz. Youth is selfless. You are loyal to us, we are loyal to you. Contract of loyalty. We want you to be one people.
	  - I want you to be obedient. People accept being obedient so that they do not have responsibility. Small peopled share the joy of success of big people.
	  - Walter Benjamin: "Fascism is aestetization of politics".
	  - Ceausescu in North Corea 1971. "Partidul Comunist Roman" channel.
	  - Fascism promised to win the war
	  - Katyn massacre, Russians captures Polish officers and massacred. NKVD.
	  - Half of killed Jews were Polish, then soviet, and others.
	  - Killings of civilians in masses was unprecedented.
	  - Carnegie report on Balkan wars. Mutual enthic cleansings. War is the perfect time to use violence against ethnic minorities.
	  - More Jews live in Argentina than in the whole Balkans.
	  - Red army raped tens of thousands of German women
	  - Comfort women. Japanese took girls as prostitutes for the army. 50k-200k.
	  - Munich conference "surrender to the huger force". France, Britain allowed Germany invading Czechoslovakia.
	  - Acropolis nazi flag.
	  - No treaty that symbolizes the end of war.
	  - USA, Britain, France didn't bomb Germany to the stone age. They wanted Germany to be on their side.
	  - Yalta conference. Fate of Eastern Europe was decided.
	  - Before WWII, USA didn't have a strong land army.
	  - Flag over the Reichstag. Perstige of communism.
	  - I love Germany so much, I'm glad ther are two of them.
	  - With NATO, Americans could deploy their military forces in Europe.
	  - Americans airlifted their army in West Berlin. Soviet Union gave up on West Berlin.
	  - Berlin is the beginning of Cold War.
	  - Iron curtain countries. Europe divided.
	  - Yugoslavia liberated itself. Tito could challange Stalin's authority.
	  - In Greece and Italy, communists were strong political powers, due to partisan movements.
	  - Bella Ciao

*** Week 13
****  End of Cold War and how Soviet union collapsed
	 - 1950's, third decade of Cold war
	 - It was believed that Cold war continues until humanity kaputt
	 - Muslims were believed to be more conservative, resistant to atheism and communism
	 - 1975 Islamic Revolution in Iran, which bordered with Soviet Union.
	 - Possibility of infiltration to USSR
	 - Invasion of Afghanistan
	 - 1981 Gdansk, Poland. Workers at tershane wanted better conditions and protested.
	 - Lech Walesa, Polish worker, later became president in post-communist Poland.
	 - 1981, military coup in Poland. Polish communist party could not assist the issue of workers. Declare seige.
	 - Polish army gained more authority, civil courts did not function.
	 - Communist parties of Hungary did not have authority over their people. Soviet tanks.
	 - In communist countries, communist regime was perceived not only as a dictatorship, but also colonization.
	 - Solidarnost, Polish movement. Gained all of sits in parliament, eliminating communists.
	 - Poland is one of the most religios countries in Europe
	 - Gerotocracy, rule of old. Westerns were joking at their funerals: good that we will come next year.
	 - Mikhail Gorbachev, 1985. "Young" when elected.
	 - Took reforms, Perestroyka and Glasnost.
	 - Perestroyka (reconstruction): Efforts to make soviet economy more functional and productive.
	 - Glasnost (transparency): People can speak freely.
	 - Hundred glowers campaign, softening in China. But people were killed.
	 - Soviet Union, the last empire, continuation of Tsarist Russia.
	 - Conflicts between Soviet republics happened.
	 - Armenians and Azerbaijanis
	 - Kyrgyz and Uzbeks
	 - Revolutions happend when repression decreases. Good dictatorship never should soften.
	 - Gorbachev was naive taht people still wanted to be part of Soviet Union.
	 - Gorbachev to Eastern Block: Don't rely on me, kıçınızı kurtarmayacağım.
	 - Solidarity took control in Poland. In other Eastern European countries, people were reluctant to use violence.
	 - Nobody like Germany's unification, both USSR and Western countires.
	 - Cold war began and ended in Berlin. Fall of Berlin wall.
	 - Since 1961, 1 million moved from East to West Germany.
	 - /The life of others/ movie.
	 - Romania: Ceausescu established person dictatorship. Nation communism. Had relative autonomy from Soviet Union.
	 - 21 december 1989, last rally of Ceausescu. He was afraid of some suspicios noise. Some arranged people protested. He is taken into custody. Romanian revolution as bloody.
	 - In other countires, it was a collective dictatorship, and they voluntarily gave up.
	 - Revolution by its definition is bloody, but in Czechoslovakia it was "velvet".
	 - /Wind of Change/ - Scorpions. Represents the optimistic movement.
	 - Chinese agreed on Perestroyka, but not on Glasnost.
	 - Protest in Tiamanmen massacre, CCP intervented with violence. Many students have been killed, hundreds of thousands arrested. 1989.
	 - China is an alternative history of communist regime. Reforms in economy, but not it politics.
	 - Military coup against Gorbachev. Gorbachev was saved by Boris Eltsin, new president of Russian Federation.
	 - With free market, prices went up. Inflation introduced. Free facilities provided by communists were gone.
	 - Already poor countries went through an economic shock.
	 - Since 1989, transition to democracy was happening all other the world. Brazil, Uruguay, Algeria, Argentina etc.
	 - Until 1990's, EU was formed of only rich countries.
	 - Spain was authoritative and fascist until 1976. Poor country. Was welcomed to EU, and tranformed economically and freedom wise.
	 - EU took Sweden, Switzerland, Finald, because they were not longer neutral, cold war was over
	 - Eastern European countries were taken in EU.
	 - European Union's carrot boosted Eastern Europe's development. They had criterias for accepting into Union.
	 - 1990's Fukuyama /the end of history?/ article. History is about political and social change, ideologies, development.
	 - Fukuyama: nobody can deny that democracy is the right system.
