#+AUTHOR: Denis Davidoglu

* ATA 121 - History of Modern Turkey
** Time & place
   - Online, 10:30-12:30
** Grading
   - Midterm 40%
   - Final 40%
   - Project 20%
   - Exam face to face
   - 5 rights not to attend classes, 70%
   - 60 or more to pass the course
** Course plan
   | Week | Topic                                                                                           |   Pages |
   |------+-------------------------------------------------------------------------------------------------+---------|
   |    1 | Introduction - The Purpose of the Course                                                        |         |
   |    2 | Decline of the Ottoman Empire (the era of Sultans Selim III and Mahmut II)                      |   21-36 |
   |    3 | Modernization era and reformation attempts in 19th century (Era of Tanzimat) and Young Ottomans |   36-50 |
   |    4 | Abdülhamit II era                                                                               |   76-93 |
   |    4 | Axis and Allied powers, Tripoli, Balkan and World War I                                         | 106-110 |
   |    5 | An international issue: Eastern Question, Secret Pacts of Ottoman territorial loss              | 110-121 |
   |    6 | Reforms of Young Turks                                                                          | 121-132 |
   |    7 | The Struggle for Independence: National Congresses in Anatolia (1919-1920)                      | 133-152 |
   |    8 | National Pact and the First Grand National Assembly in Ankara (April 23, 1920)                  | 156-160 |
   |    9 | The Eastern Front in National Resistance and Treaty of Alexandropol                             | 152-156 |
   |   10 | The Western Front and Turkish-Greek War                                                         | 155-156 |
   |   11 | Political Developments in the post-war era: The Constitution of 1921                            |         |
   |   12 | The End of War: Armistice of Mudanya and abolution of the Sultanate                             |     156 |
   |   13 | Lausanne Conference and Treaty                                                                  | 160-163 |
   |   14 | Wrap up                                                                                         |         |
** Textbook
   - [[file:docs/Eric Zürcher-Book (English).pdf][Zürcher, J.Eric, Turkey: A Modern History, 2010]]
** Notes
*** Week 1
    - 19th century history presentation.
    - Zurcher speaks Turkish fluently and is still alive.
    - Young Turks movements are similar to the reforms of the Republican Era. A continuation.
    - Mehmet the 6th the "traitor", regarded so by segments of population.
    - Kazim Karabekir, one of the friends of Mustafa Kemal Pasa.
    - Promulgation of constitution.
    - Losan Conference was a subject for many political struggles for Turks.
    - Week 8 or 9 midterm.
    - Final will have mainly the post-midterm topics.
    - Presentation topics of all students will be on exam.
    - Half an hour presentation, ~8-10 minute per person.
    - Introduce a topic, present the summary of presentation.
    - Presentations online.
    - One or two weeks will be dedicated to presentation.
    - Many historians were leftists (marxists). Niyazi Berkes was the first non-leftist historian who studied The Development of Secularism in Turkey.
    - Exam is dominated by short answer, fill in, multiple choice question. There can be a question to write short text. 
*** Week 2
**** Treaties
**** Beginning of modernization during Selim III and Mahmut II (sultan names are not important)
**** Turkish historiography
***** Official history
      - Started with 1876: first constitutional era. Amdulhamit II. First parlament with all etnicities and religions, official language Ottoman Turkish.
      - 1908: second contitutional era. Young Turks, were embracing French revolution. Justice, liberalism. Against the sultan.
      - Senate Ayan meclisi, approved the decisions of parliament.
      - 1919: Mustafa Kemal was assigned as inspector with political and military in Samsun. Also a Young Turk. Close to last sultan. Prevent clashes between Greeks and Turks in Black Sea.
      - 1923: New regime.
***** Liberal approach, focused on modernization.
      - Professors in West begin from 1980's.
      - from 1699 begins enlargment and development. beginning 1830 some territories are conqured by West. 1918-1919 partitioning of Ottoman territory.
      - Liberal approach doesnt care about territory, but about modernization.
      - 1789-1839. Selim III + mahmoud II. Selim knew about French Revolution. He opened the first ministery. Tercume odalari. Modernization of army.
      - People in Anatolia were traditional and religios, and were opposing modernizations. Selim III was killed in clashes.
      - Mahmout II was supporter of modernization too, and completed westernizations started by Selim. Promoted passports. Put pictures of himself to the official buildings. Start centralization attempts.
      - 1839-1976: Tanzimat era, Reformation era. Gulhane degree, 1856. Equality between muslims and non-muslims, especially in term of citizenchip. Security of private property. Private property of foreigners especially in trade ports. Merchants has been very powerful in this period. They formed the backbone of the senate.
      - Building of railways, improvement of education, education of girls.
      - Mahmut made primary education required.
      - American, British, French opened missionary schools all around Istanbul and Anatolia. Izmir American high school. Not connected to the Ottoman high school system. Greek, Serbian, Bulgarian community independent school. No unification of education.
      - Armenians were the first community to declare their own contitution. Imposed by nationalism of French Revolution. Serbian. Greek.
      - 1876-1909: Abdulhammit II. Opressive sultan. Closed parliament. Use force against each other. Use Britain against France in gaining power in Egypt.
      - Used fake weaponary in army??
      - Modernized education.
      - More than 100 high schools after his detronation.
      - Centralization attemps visible.
      - 31 Mart vakasi, islamists
      - 1908-1918: Young Turks era. Military should not involve in politics.
      - Women start to gain rights. They were part in uprising of occupation after WWI.
      - Halide Edib (ADIVAR). First of the women writers. Graduate of American school in Uskudar. Became professor of English literare in Istanbul University (postmortem?). Google.
      - 1919-1922: National Independence era.
      - Three important wars against Greeks, backed by English. Turks backed by Soviets.
      - In Taksim, Ataturk, Ismet Pasa, Soviet military leaders. Not Lenin of course :( 1926 by Italian architect. Symbol of Turkish-Soviet friendship.
      - 1930 USSR helped Turkey to flourished economy. Economical plans.
      - After WWII, USSR did not recognized the Bosphorus strait regime, they wanted to administrate it too. They wanted military bases in Artvin, Kars. Russian buildings there. 1876.
      - In 1917 Artvin Kars were taken back.
      - Grand national assembly had followers Mustafa and Enver pasa (Young turks). Young Turks stopped being military.
      - 1923-1946: Single party era. Exceptions 1924 - Prograssive Republic Peoples Party, MKA was furious about it in Nutuk. 1925 Kurdish uprising, supressed by the state. Commanders were trialed just to be scared. The party was said to be engaged in the uprising.
      - 1930 party, MKA founded to balance the parliament. Liberal Democrat Party. Program was written inspired form British Libral Party. In local elections, party closed itself down by the party members.
      - 1946-1950: Transition to multiparty era. Democrat party.
      - Ismet Pasa, oficer.
      - 1950-1960: DP era. Got closer to populism, religious, even though called themselves liberal. Menderes, graduate of Izmir American. First civilian president. Military coup. Prime minister, minister of foreign affairs and finance minister were executed.
      - 1961 constitution.
      - 1960-1980: Coalitions. Islamic Party, RPP-*Bulent Ecevit*.
      - Suleyman Demiral Right Justice Party.
      - 1982 Constitution still valid today.
**** Breaking points in European history
***** Affected Turkish history. Leicism is separation of state and religion. Secularism covers the individuals. The state must be laistic, but individuals can be secular.
***** Laicus X Clericus
      - Layman x Clergy.
      - Martin Luther - clergy. There should be no religious courts that promise hell or heaven.
      - Luther Calvin in Switzerland promoted ???.
      - Some religious groups could not practice their religion freely in Europe so they fled to America. Amish.
      - Amish live according to 17th century traditions. Dressing, beards, distant to technology, do not vote, 50k of them bastards. Ohio, Pensilvania. Rural areas of Chicago. Married at young age. *Documentaries of BBC*. Accept credit cards stonkssss. Use horses instead of cars.
      - Positivism by August Comte. Embracing of mind and sciend in front of religions, politics. First study of society, sociology started in France.
      - Prince Sabahattin, Abdulhamits nephew was following a French.
***** Enlightenment
      - Natural Law, Rousseau. Accroding to law, everybody has right to look for better conditions, political administration, economic inputs.
***** Industrial Revolution
      - Burgeouse formed the backbone of the state.
      - But in Turkey, non-muslims were burgeouse.
      - Brought the end of feodalism, middle ages.
***** French Revolution
      - Nation-state idea formed.
**** Anatolia in 1300.
***** Beylikler donemi, princeships. Byzantine Empire
***** Osman bey, the founder of Ottoman Princeship. 
***** Orthodox Turks have been exiled in 20th century. All christian communities were exiled. Pizdec.
*** Week 3
**** 1980's liberal professors support that in 1302 Yalova, Ottoman princeship was founded.
**** Ottoman state - quick notes
     - Turkey was not held captive by any imperial power. It was not preoccupied with the issue of colonialism
     - China, Iran, Turkey were not colonized. Marxists classify them as half-colonized.
     - Turkish modernism has its roots going to 19th century
     - The /millet/ system = "melting pot". 
     - Non-muslims were allowed to choose their own religious leaders, collect their own taxes, use their own language, and have their own *courts*.
     - With nationalism, nation-building attempts started with Serbians, Greeks and others.
     - Idea of the Ottoman nation was coming to a halt at the end of the 19th century.
**** Tanzimat era: railways and education
**** Ottoman Reformation Era
     - Selim III. Was in power in the French revolution. Wrote letters to Lewis XIII when not in power, he was prohibited to write letters to the French king.
     - Mahmoud II - started westernization
     - Sultan Abdulmecid. Military and eduction reforms. 
     - Sultan Abdulaziz. Visits to Paris, London, Brussels, Sofia. Napoleon invited to the opening of the French exhibition. Queen Victoria invited. Sultan was inspired to build new palaces. Dolmabahce, Ciragan, mosques.
     - Sultan Murat V
     - No need to know their names
**** Fossati brothers
     - Swiss
     - Visited Saint Petersburg churces
     - Instabul hagia sofia renovation
     - Iranian consulate in Cagaloglu
     - Russian embassy in Istanbul (not the same as today)
**** Balyan family
     - Armenian
     - 6-7 generations of state architects 
     - All mosques and palaces constructed by them
**** Industrial revolution
     - UK: first
     - France Germany: mid 1800s
     - Russia, Austro-Hungary, Italy: late 1800
     - Portugal, Spain, Ottoman Empire: weakly in the late 1800's
     - Watch "Charlie Chaplin Gold Rush" to understand industrial revolution. "Modern times" movie, second industrial revolutoin.
**** Napoleon Empire
     - French revolution wanted to be spread across Europe by Napoleon.
     - Made big army to export revolution
     - Coalitions against Napoleon
     - You can read "War and Peace" (Don't)
     - Monarchs gathered in Vienna 1815.
     - Ottoman Empire was not invited to join Vienna.
     - "Perpetual piece" for 100 years
     - Protection of borders
     - Gaining importance of diplomacy
**** 19th Century Ottoman State
     - Egyptian problem, Serbian problem
     - Russian influence nationalism
     - The autonomy of the minorities were in this order:
       + Direct Rule
       + Vassalage (reforms)
       + Independence
**** The dilema of Eastern Question
     - The West: Ottoman disintegration or Russian expansion?
     - Britain until the 20th century: Russian expansion should be controlled by the Ottoman Empire
     - 1853, Palestine? Crimean war. Britain, Franced backed Ottomans against Russia. Russian influence was diminshed in the middle East. (But did not lose any territory)
     - 1856: Concert of Europe
**** 18th century vs 19th century
     - Expansions of civil officials in size and function. Ex 2000 (1800s), 35000 (1908) (Males)
     - Bureaucracy increased its sphere of activity and its function. New training model, technical skills, foreign language. Greeks once were literate and higher in the society. Later muslims became literate too. Equal citizenships? Ex) Education, trade, ministries
     - Expansions of military officials
     - Britain Aydin-Izmir, France Adana-Mersin railways. They were allowed to do archeological excavations, 10km beyond the railways. Some kind of colonialism.
     - Expansion of technology: telegraph, railroad, photography.
     - New agencies: state surveillance systems
     - New politics: Local notables and central authority. Provincial administrative councils. Arab states
**** Tanzimat Era (1839-1876)
     - The center of power shifting from the palace to the Porte (Bab-i Ali), palace to bureaucracy.
     - Ottoman state extending its control into society
     - Limitation of religious authority to religious matters
     - How did the foreign powers react to these reforms
     - Marked beginning of capitalism
     - How did the masses react? The ruling class and ordinary farmer had little in common, even in language. So, hard to form a national bond. Istanbul was speaking Arabic and Persian and nobody understood the documents. Decisions superficial and masses were excluded from the central power.
     - The establishment of guarantees for life, honor, and property
     - Regular taxation, equal among muslims and non-muslims
     - Regular conscription for the army
     - Equality before the law of all
     - Rose Garden Decree (1839)
     - Second Istahal
     - Regulations in various areas. Merge Islamic law with the western one. Commercial code copied from France. Western powers had priveledges in in judiciary of the Ottoman Empire, beginning of secular courts.
     - Regulation on education. 4 types of school. State (medres), foreign (missionary), minority schools (armenians, greeks). Became state-controlled. Aimed to raise common identity and solidarity.
     - Society:
       + A la Turca vs A la Franca. Distiction started from the toilets.
       + Many writers put this distiction, Namik Kemal etc.
       + Telegraph was introduced and operated necessity for bureaucrats
       + Knoledge of European languages was a necessity for bureaucrats
       + First time of Sultan going abroad (1867)
       + Increased transportation
       + The second fenicular line in the world, after London, was constructed in Karakoy.
     - English and other traders became Ottoman citizens. Mustafa Koc (on the wealthiest families), daughter Caroline Koc is British and Turkish??
     - Middle class started to flourish
     - Newspapers and journals helped to spread new ideas and secularization
     - Non-muslims stared to serve in the bureaucracy.
     - Secularizattion started within the millets. They started to adapt their own constitution and it inspired Ottoman constitutional movement.
     - Modernization attemps. Ex. tulumbacilar Abullah brothers.
     - Opposition to reforms
       + Young Ottomans
       + Reforms wre not based on public consent, top-down reforms. Created dualism and internal struggle
       + Created by foreign powers and muslism lost their priveledges
       + Young Ottomans had western education.
       + New terminology: parliamentarism, patriotism, nationalims, progressiveness of the state with the adoption of Western policial
       + Promoted Ottomanizm
       + Namik Kemal, opposer of the Tanzimat reforms. Journalist, writer, patriotic literature piece. First one to use fatherland, freedom, public opinion, consent, contitutional government. Also islamist. Go to ages of islam and worship the sultan. (Bruh.)
       + Namik Kemal is the symbol of the fatherland, freedom, public opinion, consent, contitutional government.
       + Aliance of patriotism
       + Used the french slogans of "liberty", "brothership"..
     - Foreign Problems
       + Crete uprising: the islan held autonomus status
       + Crimean War: conflict of powes in the middle east.
     - Irish potato crisis. Sultan wanted to send 10k sterlin to Ireland. Queen requested to send 1k, because she herself sent only 2k. Secretely sent 3 ships of full of food. Drogheda united f.c.
     - Vienna congress is not included in the book
