#+AUTHOR: Denis Davidoglu

* ATA 121 - History of Modern Turkey
** Time & place
   - Online, 10:30-12:30
** Grading
   - Midterm 40%
   - Final 40%
   - Project 20%
   - Exam face to face
   - 5 rights not to attend classes, 70%
   - 60 or more to pass the course
** Course plan
** Textbook
** Notes
*** Week 1
    - 19th century history presentation.
    - Zurcher speaks Turkish fluently and is still alive.
    - Young Turks movements are similar to the reforms of the Republican Era. A continuation.
    - Mehmet the 6th the "traitor", regarded so by segments of population.
    - Kazim Karabekir, one of the friends of Mustafa Kemal Pasa.
    - Promulgation of constitution.
    - Losan Conference was a subject for many political struggles for Turks.
    - Week 8 or 9 midterm.
    - Final will have mainly the post-midterm topics.
    - Presentation topics of all students will be on exam.
    - Half an hour presentation, ~8-10 minute per person.
    - Introduce a topic, present the summary of presentation.
    - Presentations online.
    - One or two weeks will be dedicated to presentation.
    - Many historians were leftists (marxists). Niyazi Berkes was the first non-leftist historian who studied The Development of Secularism in Turkey.
    - Exam is dominated by short answer, fill in, multiple choice question. There can be a question to write short text. 
*** Week 2
**** Treaties
**** Beginning of modernization during Selim III and Mahmut II (sultan names are not important)
**** Turkish historiography
***** Official history
      - Started with 1876: first constitutional era. Amdulhamit II. First parlament with all etnicities and religions, official language Ottoman Turkish.
      - 1908: second contitutional era. Young Turks, were embracing French revolution. Justice, liberalism. Against the sultan.
      - Senate Ayan meclisi, approved the decisions of parliament.
      - 1919: Mustafa Kemal was assigned as inspector with political and military in Samsun. Also a Young Turk. Close to last sultan. Prevent clashes between Greeks and Turks in Black Sea.
      - 1923: New regime.
***** Liberal approach, focused on modernization.
      - Professors in West begin from 1980's.
      - from 1699 begins enlargment and development. beginning 1830 some territories are conqured by West. 1918-1919 partitioning of Ottoman territory.
      - Liberal approach doesnt care about territory, but about modernization.
      - 1789-1839. Selim III + mahmoud II. Selim knew about French Revolution. He opened the first ministery. Tercume odalari. Modernization of army.
      - People in Anatolia were traditional and religios, and were opposing modernizations. Selim III was killed in clashes.
      - Mahmout II was supporter of modernization too, and completed westernizations started by Selim. Promoted passports. Put pictures of himself to the official buildings. Start centralization attempts.
      - 1839-1976: Tanzimat era, Reformation era. Gulhane degree, 1856. Equality between muslims and non-muslims, especially in term of citizenchip. Security of private property. Private property of foreigners especially in trade ports. Merchants has been very powerful in this period. They formed the backbone of the senate.
      - Building of railways, improvement of education, education of girls.
      - Mahmut made primary education required.
      - American, British, French opened missionary schools all around Istanbul and Anatolia. Izmir American high school. Not connected to the Ottoman high school system. Greek, Serbian, Bulgarian community independent school. No unification of education.
      - Armenians were the first community to declare their own contitution. Imposed by nationalism of French Revolution. Serbian. Greek.
      - 1876-1909: Abdulhammit II. Opressive sultan. Closed parliament. Use force against each other. Use Britain against France in gaining power in Egypt.
      - Used fake weaponary in army??
      - Modernized education.
      - More than 100 high schools after his detronation.
      - Centralization attemps visible.
      - 31 Mart vakasi, islamists
      - 1908-1918: Young Turks era. Military should not involve in politics.
      - Women start to gain rights. They were part in uprising of occupation after WWI.
      - Halide Edib (ADIVAR). First of the women writers. Graduate of American school in Uskudar. Became professor of English literare in Istanbul University (postmortem?). Google.
      - 1919-1922: National Independence era.
      - Three important wars against Greeks, backed by English. Turks backed by Soviets.
      - In Taksim, Ataturk, Ismet Pasa, Soviet military leaders. Not Lenin of course :( 1926 by Italian architect. Symbol of Turkish-Soviet friendship.
      - 1930 USSR helped Turkey to flourished economy. Economical plans.
      - After WWII, USSR did not recognized the Bosphorus strait regime, they wanted to administrate it too. They wanted military bases in Artvin, Kars. Russian buildings there. 1876.
      - In 1917 Artvin Kars were taken back.
      - Grand national assembly had followers Mustafa and Enver pasa (Young turks). Young Turks stopped being military.
      - 1923-1946: Single party era. Exceptions 1924 - Prograssive Republic Peoples Party, MKA was furious about it in Nutuk. 1925 Kurdish uprising, supressed by the state. Commanders were trialed just to be scared. The party was said to be engaged in the uprising.
      - 1930 party, MKA founded to balance the parliament. Liberal Democrat Party. Program was written inspired form British Libral Party. In local elections, party closed itself down by the party members.
      - 1946-1950: Transition to multiparty era. Democrat party.
      - Ismet Pasa, oficer.
      - 1950-1960: DP era. Got closer to populism, religious, even though called themselves liberal. Menderes, graduate of Izmir American. First civilian president. Military coup. Prime minister, minister of foreign affairs and finance minister were executed.
      - 1961 constitution.
      - 1960-1980: Coalitions. Islamic Party, RPP-*Bulent Ecevit*.
      - Suleyman Demiral Right Justice Party.
      - 1982 Constitution still valid today.
**** Chat link: https://chat.whatsapp.com/CgHs7CxjgejDTLvkIWRdyZ
**** Breaking points in European history
***** Affected Turkish history. Leicism is separation of state and religion. Secularism covers the individuals. The state must be laistic, but individuals can be secular.
***** Laicus X Clericus
      - Layman x Clergy.
      - Martin Luther - clergy. There should be no religious courts that promise hell or heaven.
      - Luther Calvin in Switzerland promoted ???.
      - Some religious groups could not practice their religion freely in Europe so they fled to America. Amish.
      - Amish live according to 17th century traditions. Dressing, beards, distant to technology, do not vote, 50k of them bastards. Ohio, Pensilvania. Rural areas of Chicago. Married at young age. *Documentaries of BBC*. Accept credit cards stonkssss. Use horses instead of cars.
      - Positivism by August Comte. Embracing of mind and sciend in front of religions, politics. First study of society, sociology started in France.
      - Prince Sabahattin, Abdulhamits nephew was following a French.
***** Enlightenment
      - Natural Law, Rousseau. Accroding to law, everybody has right to look for better conditions, political administration, economic inputs.
***** Industrial Revolution
      - Burgeouse formed the backbone of the state.
      - But in Turkey, non-muslims were burgeouse.
      - Brought the end of feodalism, middle ages.
***** French Revolution
      - Nation-state idea formed.
**** Anatolia in 1300.
***** Beylikler donemi, princeships. Byzantine Empire
***** Osman bey, the founder of Ottoman Princeship. 
***** Orthodox Turks have been exiled in 20th century. All christian communities were exiled. Pizdec.

